# Generated by Django 5.2.1 on 2025-05-23 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_actual_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useractivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="analytics.user",
            ),
        ),
        migrations.DeleteModel(
            name="ChatUser",
        ),
    ]
