# Generated by Django 5.2.1 on 2025-05-23 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0003_alter_useractivity_user_delete_chatuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"managed": False},
        ),
        migrations.AlterModelOptions(
            name="useractivity",
            options={"managed": False},
        ),
    ]
