# Generated by Django 5.2.1 on 2025-05-23 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0004_alter_message_options_alter_useractivity_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useractivity",
            name="user",
        ),
        migrations.DeleteModel(
            name="Message",
        ),
        migrations.DeleteModel(
            name="UserActivity",
        ),
    ]
